# SPDX-FileCopyrightText: 2023 Kevin de Jong <monkaii@hotmail.com>
#
# SPDX-License-Identifier: CC0-1.0

name: 'CommitMe - Conventional Commits validation'
author: 'Kevin de Jong'
description: >
  Validate your Pull Request against the Conventional Commits specification.

branding:
  icon: 'code'  
  color: 'white'

inputs:
  token: 
    description: 'GitHub token used to access GitHub (eg. github.token)'
    required: true
  
  update-labels:
    description: 'Update labels on Pull Request (`breaking`, `feature` or `fix`)'
    required: false
    default: true

runs:
  using: 'node16'
  main: 'lib/action/index.js'
