# SPDX-FileCopyrightText: 2023 Kevin de Jong <monkaii@hotmail.com>
# SPDX-License-Identifier: MIT

name: 'CommitMe - Conventional Commits validation'
author: 'Kevin de Jong'
description: >
  Validate your Pull Request against the Conventional Commits specification.

branding:
  icon: 'code'  
  color: 'white'

inputs:
  token: 
    description: 'GitHub token used to access GitHub (eg. github.token)'
    required: false
  
  update-labels:
    description: 'Update labels on Pull Request (`breaking`, `feature` or `fix`)'
    required: false
    default: true
  
  include-commits:
    description: 'Include commits associated with the Pull Request; by default we use the repository configuration settings to determine this value.'
    required: false
  
  scopes:
    description: 'Conventional Commits scopes allowed for this repository; be default we accept all scopes.'
    required: false
  
  types:
    description: 'Conventional Commits types allowed for this repository; by default we accept all types.'
    required: false

runs:
  using: 'node16'
  main: 'lib/action/index.js'
